spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: compras-service
  datasource:
    url: ${PURCHASES_DB_URL:jdbc:mysql://100.92.51.27:3306/db_purchases?createDatabaseIfNotExist=true&serverTimezone=UTC}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${PURCHASES_DB_USERNAME:${DB_USERNAME:equipo}}
    password: ${PURCHASES_DB_PASSWORD:${DB_PASSWORD}}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: ${PURCHASES_PORT:8082}
  servlet:
    context-path: /api/v1

jwt:
  secret: ${JWT_SECRET}

catalog:
  base-url: ${PRODUCTOS_SERVICE_URL:http://localhost:3001}